### ISSUE TITLE
Allow incrementing/decreasing by custom number

### ISSUE THREAD

**Issue by anotherus3r** [quicksc0p3r/simplecounter#45] opened 2024-11-06 09:20 UTC
Hi, 

would be great if we could be able to set a counter to be able to increase/decrease a counter by a custom value, which is a use-case I often have a need for.

E.g. in other counting apps, I often create a counter that I use for general counting and name them something like +10, +20, etc. and then set the default value for increasing the counter to e.g. +10, +20, etc. So when I tap the + button it increments the value by 10, which can be quicker (and less likely that I miss to increment the counter) instead of tapping the + button for every single item I count. Then I keep the value for decreasing at -1 in case the final number is not rounded.

**Comment by quicksc0p3r** [comment] 2024-11-09 08:36
Closed as duplicate of #13.

Math operation functionality was added recently, does that fit your use case?

**Closed by quicksc0p3r** 2024-11-09 08:36 UTC
